### ISSUE TITLE
install fails on steam deck 

### ISSUE THREAD

**Issue by grasshacques** [primetime00/memory_hack#4]
This is the console output when I try to install

```
gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/deck/venv/include -I/usr/include/python3.11 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-cpython-311/psutil/_psutil_common.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: /home/deck/venv/bin/python3 -m pip install --upgrade pip
Traceback (most recent call last):
  File "/home/deck/install.py", line 197, in <module>
    create_venv()
  File "/home/deck/install.py", line 51, in create_venv
    subprocess.check_call(['./venv/bin/python3', "-m", "pip", "install", "-r", "app/patches/requirements.txt"])
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./venv/bin/python3', '-m', 'pip', 'install', '-r', 'app/patches/requirements.txt']' returned non-zero exit status 1.

```

**Comment by primetime00** [comment]
Can you paste the entire output of the install.  I just tried to reinstall my version to see if something changed.  I get the folowing
```
python3 <(wget -qO- https://github.com/primetime00/memory_hack/raw/master/app/patches/install.py)
downloading source
extracting...
creating virtual environment...
Collecting falcon==3.1.0
  Using cached falcon-3.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.5 MB)
Collecting falcon-multipart==0.2.0
  Using cached falcon_multipart-0.2.0-py3-none-any.whl (5.2 kB)
Collecting gunicorn==20.1.0
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting mem-edit==0.6
  Using cached mem_edit-0.6-py3-none-any.whl (24 kB)
Collecting psutil==5.9.1
  Using cached psutil-5.9.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting typing==3.7.4.3
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools>=3.0 in ./venv/lib/python3.10/site-packages (from gunicorn==20.1.0->-r app/patches/requirements.txt (line 3)) (63.2.0)
Using legacy 'setup.py install' for typing, since package 'wheel' is not installed.
Installing collected packages: typing, psutil, gunicorn, falcon, mem-edit, falcon-multipart
  Running setup.py install for typing ... done
Successfully installed falcon-3.1.0 falcon-multipart-0.2.0 gunicorn-20.1.0 mem-edit-0.6 psutil-5.9.1 typing-3.7.4.3

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: /home/deck/memory_hack/venv/bin/python3 -m pip install --upgrade pip
patching memory editor
extracting front-end...

Would you like to install Memory Hack as a service? (y/n): y
Running sudo...
installing service!
Created symlink /etc/systemd/system/multi-user.target.wants/memory_hack.service → /etc/systemd/system/memory_hack.service.
Service installation complete.
You can test by accessing http://steamdeck:5000.
```
So it is still working on my side.

**Comment by BooBerry** [comment]
I'm seeing this too upon installing SteamOS 3.5 Preview. It was working fine in SteamOS 3.4.8 previously.

**Comment by primetime00** [comment]
I will try it out.
