### ISSUE TITLE
python install.py fail on Win 10 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired 

### ISSUE THREAD

**Issue by kondeeza** [primetime00/memory_hack#8]
This is the console output when I try to install on Windows 10

> Traceback (most recent call last):
  File "C:\Users\\Downloads\memoryhack\install.py", line 245, in <module>
    download_nssm()
  File "C:\Users\\Downloads\memoryhack\install.py", line 36, in download_nssm
    request.urlretrieve(remote_url, local_file)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
PS C:\Users\\Downloads\memoryhack>

SSL possibly expired?

**Comment by primetime00** [comment]
Looks like the site for nssm has cert issues.  Let me see if I can find a mirror.  Maybe nssm can be placed in this repo.

**Comment by primetime00** [comment]
Try to recreate a new directory and run the install again.  I changed the script so it does not depend on nssm's site.

**Comment by kondeeza** [comment]
Can install just fine now, thanks !
